package com.alpascal.api.videostreamingapi.records

data class Video(
    val id: String,
    val name: String,
    val duration: String,
    val iconURL: String,
    val thumbnailURL: String,
    val creatorName: String,
    val viewCount: String,
    val timeSincePublished: String,
    val isCreatorVerified: Boolean = false,
) {
    companion object {
        private val dynamicVideoIndexList = listOf(0, 1, 2)
        private val videos = listOf(
            Video(
                id = "1",
                name = "10 Amazing Facts You Didn't Know!",
                duration = "15:23",
                iconURL = "https://via.placeholder.com/150",
                thumbnailURL = "https://bit.ly/2Z4KKcF",
                creatorName = "FactMaster",
                viewCount = "1,000",
                timeSincePublished = "1 day ago",
                isCreatorVerified = false,
            ),
            Video(
                id = "2",
                name = "How to Cook the Perfect Steak",
                duration = "25:45",
                iconURL = "https://via.placeholder.com/150",
                thumbnailURL = "https://bit.ly/2Z4KKcF",
                creatorName = "ChefGordon",
                viewCount = "2,000",
                timeSincePublished = "2 months ago",
                isCreatorVerified = true,
            ),
            Video(
                id = "3",
                name = "Top 20 Travel Destinations You Must Visit Before You Die",
                duration = "35:12",
                iconURL = "https://via.placeholder.com/150",
                thumbnailURL = "https://bit.ly/2Z4KKcF",
                creatorName = "TravelGuru",
                viewCount = "3,000",
                timeSincePublished = "3 years ago",
                isCreatorVerified = false,
            ),
            Video(
                id = "4",
                name = "The Ultimate Guide to Investing",
                duration = "45:30",
                iconURL = "https://via.placeholder.com/150",
                thumbnailURL = "https://bit.ly/2Z4KKcF",
                creatorName = "FinanceExpert",
                viewCount = "4,000",
                timeSincePublished = "4 hours ago",
                isCreatorVerified = false,
            ),
            Video(
                id = "5",
                name = "10 Minute Morning Yoga Routine to Start Your Day Right",
                duration = "10:00",
                iconURL = "https://via.placeholder.com/150",
                thumbnailURL = "https://bit.ly/2Z4KKcF",
                creatorName = "YogaWithAnna",
                viewCount = "5,000",
                timeSincePublished = "5 minutes ago",
                isCreatorVerified = true,
            ),
            Video(
                id = "6",
                name = "DIY Home Decor Ideas",
                duration = "20:15",
                iconURL = "https://via.placeholder.com/150",
                thumbnailURL = "https://bit.ly/2Z4KKcF",
                creatorName = "CraftyHands",
                viewCount = "6,000",
                timeSincePublished = "6 days ago",
                isCreatorVerified = false,
            ),
            Video(
                id = "7",
                name = "The Science Behind Sleep and How to Improve Your Sleep Quality",
                duration = "30:45",
                iconURL = "https://via.placeholder.com/150",
                thumbnailURL = "https://bit.ly/2Z4KKcF",
                creatorName = "SleepDoctor",
                viewCount = "7,000",
                timeSincePublished = "7 months ago",
                isCreatorVerified = true,
            ),
            Video(
                id = "8",
                name = "Unboxing the Latest Tech Gadgets",
                duration = "40:10",
                iconURL = "https://via.placeholder.com/150",
                thumbnailURL = "https://bit.ly/2Z4KKcF",
                creatorName = "TechGuru",
                viewCount = "8,000",
                timeSincePublished = "8 years ago",
                isCreatorVerified = false,
            ),
            Video(
                id = "9",
                name = "Beginner's Guide to Meditation",
                duration = "10:05",
                iconURL = "https://via.placeholder.com/150",
                thumbnailURL = "https://bit.ly/2Z4KKcF",
                creatorName = "MindfulMike",
                viewCount = "9,000",
                timeSincePublished = "9 hours ago",
                isCreatorVerified = false,
            ),
            Video(
                id = "10",
                name = "Epic Fails Compilation",
                duration = "12:30",
                iconURL = "https://via.placeholder.com/150",
                thumbnailURL = "https://bit.ly/2Z4KKcF",
                creatorName = "FunnyFails",
                viewCount = "10,000",
                timeSincePublished = "10 minutes ago",
                isCreatorVerified = true,
            ),
            Video(
                id = "11",
                name = "The Complete History of Ancient Egypt: From Pharaohs to Pyramids",
                duration = "50:00",
                iconURL = "https://via.placeholder.com/150",
                thumbnailURL = "https://bit.ly/2Z4KKcF",
                creatorName = "HistoryBuff",
                viewCount = "11,000",
                timeSincePublished = "11 days ago",
                isCreatorVerified = false,
            ),
            Video(
                id = "12",
                name = "The Best Movie Trailers of 2023: A Comprehensive Review",
                duration = "22:15",
                iconURL = "https://via.placeholder.com/150",
                thumbnailURL = "https://bit.ly/2Z4KKcF",
                creatorName = "MovieMania",
                viewCount = "12,000",
                timeSincePublished = "12 months ago",
                isCreatorVerified = true,
            ),
            Video(
                id = "13",
                name = "How to Build a Gaming PC",
                duration = "55:45",
                iconURL = "https://via.placeholder.com/150",
                thumbnailURL = "https://bit.ly/2Z4KKcF",
                creatorName = "GamerGuy",
                viewCount = "13,000",
                timeSincePublished = "13 years ago",
                isCreatorVerified = false,
            ),
            Video(
                id = "14",
                name = "The Best Workout for Weight Loss",
                duration = "35:00",
                iconURL = "https://via.placeholder.com/150",
                thumbnailURL = "https://bit.ly/2Z4KKcF",
                creatorName = "FitnessFreak",
                viewCount = "14,000",
                timeSincePublished = "14 hours ago",
                isCreatorVerified = false,
            ),
            Video(
                id = "15",
                name = "Top 20 Life Hacks You Need to Know to Simplify Your Life",
                duration = "18:30",
                iconURL = "https://via.placeholder.com/150",
                thumbnailURL = "https://bit.ly/2Z4KKcF",
                creatorName = "LifeHacker",
                viewCount = "15,000",
                timeSincePublished = "15 minutes ago",
                isCreatorVerified = true,
            ),
            Video(
                id = "16",
                name = "Exploring the Amazon Rainforest",
                duration = "45:20",
                iconURL = "https://via.placeholder.com/150",
                thumbnailURL = "https://bit.ly/2Z4KKcF",
                creatorName = "NatureLover",
                viewCount = "16,000",
                timeSincePublished = "16 days ago",
                isCreatorVerified = false,
            ),
            Video(
                id = "17",
                name = "The Ultimate Guide to Photography",
                duration = "50:10",
                iconURL = "https://via.placeholder.com/150",
                thumbnailURL = "https://bit.ly/2Z4KKcF",
                creatorName = "PhotoPro",
                viewCount = "17,000",
                timeSincePublished = "17 months ago",
                isCreatorVerified = true,
            ),
            Video(
                id = "18",
                name = "How to Play the Guitar for Beginners",
                duration = "25:00",
                iconURL = "https://via.placeholder.com/150",
                thumbnailURL = "https://bit.ly/2Z4KKcF",
                creatorName = "GuitarGuru",
                viewCount = "18,000",
                timeSincePublished = "18 years ago",
                isCreatorVerified = false,
            ),
            Video(
                id = "19",
                name = "The Best Street Food Around the World",
                duration = "30:30",
                iconURL = "https://via.placeholder.com/150",
                thumbnailURL = "https://bit.ly/2Z4KKcF",
                creatorName = "Foodie",
                viewCount = "19,000",
                timeSincePublished = "19 hours ago",
                isCreatorVerified = false,
            ),
            Video(
                id = "20",
                name = "Top 10 Video Games of All Time",
                duration = "40:45",
                iconURL = "https://via.placeholder.com/150",
                thumbnailURL = "https://bit.ly/2Z4KKcF",
                creatorName = "GamerZone",
                viewCount = "20,000",
                timeSincePublished = "20 minutes ago",
                isCreatorVerified = true,
            ),
            Video(
                id = "21",
                name = "How to Start a Successful YouTube Channel",
                duration = "55:00",
                iconURL = "https://via.placeholder.com/150",
                thumbnailURL = "https://bit.ly/2Z4KKcF",
                creatorName = "YouTubePro",
                viewCount = "21,000",
                timeSincePublished = "21 days ago",
                isCreatorVerified = false,
            ),
            Video(
                id = "22",
                name = "The Best Books to Read in 2023: A Curated List for Avid Readers",
                duration = "20:20",
                iconURL = "https://via.placeholder.com/150",
                thumbnailURL = "https://bit.ly/2Z4KKcF",
                creatorName = "BookWorm",
                viewCount = "22,000",
                timeSincePublished = "22 months ago",
                isCreatorVerified = true,
            ),
            Video(
                id = "23",
                name = "How to Make Money Online",
                duration = "35:35",
                iconURL = "https://via.placeholder.com/150",
                thumbnailURL = "https://bit.ly/2Z4KKcF",
                creatorName = "MoneyMaker",
                viewCount = "23,000",
                timeSincePublished = "23 years ago",
                isCreatorVerified = false,
            ),
            Video(
                id = "24",
                name = "The Ultimate Guide to Gardening",
                duration = "45:45",
                iconURL = "https://via.placeholder.com/150",
                thumbnailURL = "https://bit.ly/2Z4KKcF",
                creatorName = "GreenThumb",
                viewCount = "24,000",
                timeSincePublished = "24 hours ago",
                isCreatorVerified = false,
            )
        )

        private fun getVideoList(tag: String): List<Video> {
            val newVideoList = videos.toMutableList()
            for(index in dynamicVideoIndexList) {
                var video = newVideoList[index]
                val tagTag = DynamicVideo.mapStringToTag(tag)
                val name = DynamicVideo.getName(index, tagTag)
                val thumbnailURL = DynamicVideo.getThumbnailURL(index, tagTag)
                name?.let { video = video.copy(name = it) }
                thumbnailURL?.let { video = video.copy(thumbnailURL = it) }
                newVideoList[index] = video
            }
            return newVideoList
        }

        @JvmStatic
        fun getById(id: String): Video =
            videos.find { it.id == id } ?: Video(
                id = "0",
                name = "",
                duration = "",
                iconURL = "",
                thumbnailURL = "",
                creatorName = "",
                viewCount = "",
                timeSincePublished = "",
            )

        fun getAll(tag: String): List<Video> = getVideoList(tag)
    }
}
